global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: load_balancer
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    dns_sd_configs:
      - names: [ "load_balancer" ]
        type: "A"
        port: 8082

  - job_name: api
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    dns_sd_configs:
      - names: [ "api" ]
        type: "A"
        port: 8080
        
  - job_name: "dotnet_monitor"
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["dotnet_monitor:52323"]